version: '3.3'
services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'rest_api'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '3306:${DB_PORT}'
        expose:
            - '${DB_PORT}'
        volumes:
            - my-db:/var/lib/mysql
# Names our volume
volumes:
    my-db:
